# Generated by Django 2.2 on 2019-04-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasjon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
