# Generated by Django 2.2 on 2019-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasjon', '0003_auto_20190407_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='performances',
            field=models.ManyToManyField(related_name='production', to='reservasjon.Performance'),
        ),
    ]
