# Generated by Django 2.2 on 2019-04-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, related_name='performance', to='reservation.TicketType'),
        ),
        migrations.AlterField(
            model_name='production',
            name='performances',
            field=models.ManyToManyField(blank=True, related_name='production', to='reservation.Performance'),
        ),
        migrations.AlterField(
            model_name='production',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, related_name='production', to='reservation.TicketType'),
        ),
    ]
