# Generated by Django 2.2 on 2019-04-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190418_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='performances',
        ),
        migrations.AddField(
            model_name='performance',
            name='production',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='reservation.Production'),
            preserve_default=False,
        ),
    ]
