# Generated by Django 2.2 on 2019-04-18 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190418_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='theatre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='reservation.Theatre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, help_text='Hvilke type billetter som selges i denne produksjonen', limit_choices_to={'theatre': django.db.models.expressions.F('theatre')}, related_name='production', to='reservation.TicketType'),
        ),
    ]
