# Generated by Django 2.2 on 2019-04-18 21:45

from django.db import migrations, models
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190418_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, help_text='Hvilke type billetter som selges i denne produksjonen', limit_choices_to={'theatre': django.db.models.expressions.F('Theatre')}, related_name='production', to='reservation.TicketType'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
